import {
  cibAmazonAws,
  cibAzureDevops,
  cibDjango,
  cibDocker,
  cibEslint,
  cibFirebase,
  cibGithub,
  cibGitlab,
  cibGoogleAnalytics,
  cibGoogleCloud,
  cibGraphql,
  cibJavascript,
  cibNextJs,
  cibNodeJs,
  cibPostgresql,
  cibPostman,
  cibPrettier,
  cibPython,
  cibReact,
  cibRedis,
  cibRedux,
  cibTwilio,
  cibTypescript,
  cibUpwork,
  cibVueJs,
} from "@coreui/icons";

export const brand = {
  react: cibReact,
  next: cibNextJs,
  javascript: cibJavascript,
  typescript: cibTypescript,
  python: cibPython,
  redis: cibRedis,
  gcp: cibGoogleCloud,
  gtm: cibGoogleAnalytics,
  github: cibGithub,
  gitlab: cibGitlab,
  aws: cibAmazonAws,
  azure: cibAzureDevops,
  django: cibDjango,
  docker: cibDocker,
  firebase: cibFirebase,
  node: cibNodeJs,
  postman: cibPostman,
  prettier: cibPrettier,
  eslint: cibEslint,
  redux: cibRedux,
  vue: cibVueJs,
  twilio: cibTwilio,
  upwork: cibUpwork,
  graphql: cibGraphql,
  psql: cibPostgresql,
};
